//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public short ID_cliente { get; set; }
        public string Nome_razaoSocial { get; set; }
        public string CPF_CNPJ { get; set; }
        public string Nome_fantasia { get; set; }
        public string Celular { get; set; }
        public string TelFixo { get; set; }
        public string TelComercial { get; set; }
        public string Rua { get; set; }
        public short Numero { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public bool Flag_cliente { get; set; }
    }
}
