//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESSOA_JURIDICA
    {
        public string Razao_social { get; set; }
        public string Nome_fantasia { get; set; }
        public string CNPJ { get; set; }
        public string Nome_contato { get; set; }
        public short ID_cliente { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
