//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public short ID_usuario { get; set; }
        public string Nome_usuario { get; set; }
        public string CPF_usuario { get; set; }
        public string Senha_usuario { get; set; }
        public bool Flag_usuario { get; set; }
    }
}
